name: Main Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-compiler:
          - 4.10.0
        skip_test:
          - false

        include:
          - os: ubuntu-latest
            ocaml-compiler: 4.07.0
            skip_test: true


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve opam cache
        uses: actions/cache@v2
        id: cache-opam
        with:
          path: ~/.opam
          key: v2-${{ runner.os }}-ez_cmdliner-${{ matrix.ocaml-compiler }}-${{ hashFiles('*.opam') }}
#          restore-keys: |
#            v2-${{ runner.os }}-opam-${{ matrix.ocaml-compiler }}-

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com

      # define opam-repo = "git+https://" to add an extra opam repo

      - run: opam pin add . -y --no-action

      - run: opam depext -y ez_cmdliner
#        if: steps.cache-opam.outputs.cache-hit != 'true'

      - run: opam install -y ./*.opam --deps-only --with-test
#        if: steps.cache-opam.outputs.cache-hit != 'true'

#      - run: opam upgrade --fixup
#        if: steps.cache-opam.outputs.cache-hit == 'true'

      - run: dos2unix scripts/*.sh
        if: matrix.os == 'windows-latest'

      - run: make build

      - name: run test suite
        run: |
          ./scripts/before.sh test
          opam exec -- dune build @runtest
          ./scripts/after.sh test
        if: matrix.skip_test  != 'true'

      - name: test source is well formatted
        run: make fmt
        continue-on-error: true
        if: matrix.ocaml-compiler == '4.10.0' && matrix.os == 'ubuntu-latest'
